# Generated by Django 4.2.6 on 2024-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cAficion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cApellido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cCalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cCatalagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seleccion', models.CharField(max_length=25)),
                ('Nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cColonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cTpPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='mDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvCalle', models.IntegerField()),
                ('Numero', models.IntegerField()),
                ('CvColonia', models.IntegerField()),
                ('CvMunicipio', models.IntegerField()),
                ('CvCiudad', models.IntegerField()),
                ('CodPos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mDtPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curp', models.CharField(max_length=18)),
                ('CvNombre', models.IntegerField()),
                ('ApePat', models.IntegerField()),
                ('ApeMat', models.IntegerField()),
                ('CvDireccion', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('E_mail', models.CharField(max_length=30)),
                ('CvGenero', models.IntegerField()),
                ('CvTrabajo', models.IntegerField()),
                ('FecNac', models.DateField()),
                ('CvTpPerson', models.IntegerField()),
                ('CvAficion', models.IntegerField()),
                ('Notas', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='mRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvUsuario', models.IntegerField()),
                ('CvPerson', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvPerson', models.IntegerField()),
                ('Login', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('FecIni', models.DateField()),
                ('FecFin', models.DateField()),
                ('EdoCta', models.BooleanField()),
            ],
        ),
    ]
