# Generated by Django 4.2.6 on 2024-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mAplicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvAplicaciones', models.CharField(max_length=15)),
                ('DsAplicacion', models.CharField(max_length=25)),
                ('Nivel', models.IntegerField()),
            ],
        ),
    ]
