# Generated by Django 4.2.6 on 2024-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0004_alter_maplicaciones_cvaplicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='mAccesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvUsuario', models.IntegerField()),
                ('CvAplicacion', models.IntegerField()),
                ('DsAplicaciones', models.CharField(max_length=6)),
            ],
        ),
    ]
