# Generated by Django 4.2.6 on 2024-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0008_remove_tventas_cvproducto_tventas_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='mPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.IntegerField()),
                ('Proveedor', models.IntegerField()),
                ('FechaPedido', models.DateField()),
                ('FechaEntrega', models.DateField()),
                ('SubTotal', models.FloatField()),
                ('Impuesto', models.FloatField()),
                ('Total', models.FloatField()),
                ('Pagado', models.BooleanField()),
                ('Recibido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvPedido', models.IntegerField()),
                ('Codigo', models.CharField(max_length=13)),
                ('PrecioPedido', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('SubTot', models.FloatField()),
            ],
        ),
    ]
