# Generated by Django 4.2.6 on 2024-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0010_listafaltantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='mRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.IntegerField()),
                ('Proveedor', models.IntegerField()),
                ('FechaPedido', models.DateField()),
                ('FechaRecepcion', models.DateField()),
                ('SubTotal', models.FloatField()),
                ('Impuesto', models.FloatField()),
                ('Total', models.FloatField()),
                ('Observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvRecepcion', models.IntegerField()),
                ('Codigo', models.CharField(max_length=13)),
                ('PrecioRecepcion', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('SubTot', models.FloatField()),
                ('Observacion', models.CharField(max_length=200)),
            ],
        ),
    ]
