# Generated by Django 4.2.6 on 2024-09-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0011_mrecepcion_trecepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='cConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cTpTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='mCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.FloatField()),
                ('CvVenta', models.IntegerField()),
                ('EdoCorte', models.BooleanField()),
                ('FecMovim', models.DateField()),
                ('Empleado', models.IntegerField()),
                ('FecCorte', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mCajaGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anterior', models.FloatField()),
                ('Monto', models.FloatField()),
                ('Actual', models.FloatField()),
                ('CvTpTransaccion', models.IntegerField()),
                ('CvConcepto', models.IntegerField()),
                ('InfConcepto', models.IntegerField()),
                ('Empleado', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mCorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.IntegerField()),
                ('Monto', models.FloatField()),
                ('Diferencia', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
            ],
        ),
    ]
