# Generated by Django 4.2.6 on 2024-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0012_cconcepto_ctptransaccion_mcajachica_mcajagrande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcajachica',
            name='FecCorte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
