# Generated by Django 4.2.6 on 2024-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0013_alter_mcajachica_feccorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpedidos',
            name='Anticipo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
