# Generated by Django 4.2.6 on 2024-10-09 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0014_mpedidos_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproductos',
            name='FechaCaducidad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
