# Generated by Django 4.2.6 on 2024-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0015_mproductos_fechacaducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdtperson',
            name='Telefono',
            field=models.CharField(max_length=20),
        ),
    ]
